### ISSUE TITLE
hey hi

### ISSUE THREAD

**Issue by derekleverenz** [ivanov/bipython#2]
Hey, 

talked earlier today at pycon. Here is an issue, as promised. Ima take a look at the bpython code and see whats up.

**Comment by ivanov** [comment]
hey, it only took a year for me to start, but i've got a working version that's in reasonable shape here - only been working on it since Sunday.

**Comment by derekleverenz** [comment]
awesome, I just saw a bunch of emails about it and was excited. Hopefully i'll be able to contribute something useful, work is super busy right now, we just launched our first thing. This is rad though.
